#cloud-config
hostname: ${HOSTNAME}
disable_root: false
ssh_pwauth: true
package_update: true
packages:
  - vim
  - jq
  - curl
users:
  - name: root
    ssh-authorized-keys:
      - ${file("id_rsa.pub")}
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    passwd: '$1$QOC9yL8J$/Qmip/cG0/snuxfwJsQqN1'
    ssh-authorized-keys:
      - ${file("id_rsa.pub")}
    groups: docker
growpart:
  mode: auto
  devices: ['/']
